//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mollaev.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int IdContract { get; set; }
        public Nullable<int> IdStorageRooms { get; set; }
        public string RentalType { get; set; }
        public System.DateTime DateOfConclusion { get; set; }
        public System.DateTime EndDate { get; set; }
        public int IdLandlord { get; set; }
        public int IdTenant { get; set; }
        public int IdRates { get; set; }
    
        public virtual Landlord Landlord { get; set; }
        public virtual Rates Rates { get; set; }
        public virtual StorageRooms StorageRooms { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
