//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mollaev.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Landlord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Landlord()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        public int IdLandlord { get; set; }
        public string LastNameLandlord { get; set; }
        public string FirstNameLandlord { get; set; }
        public string MiddleNameLandlord { get; set; }
        public string PhoneLandlord { get; set; }
        public string EmailLandlord { get; set; }
        public string SerPass { get; set; }
        public string NumberPass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
    }
}
