//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mollaev.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageRooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StorageRooms()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        public int IdStorageRooms { get; set; }
        public int IdAddress { get; set; }
        public string Area { get; set; }
        public int StorageСapacity { get; set; }
        public string NameStorageRooms { get; set; }
        public string ViewStorageRooms { get; set; }
        public int IdStatus { get; set; }
        public byte[] PhotoStorageRooms { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual Status Status { get; set; }
    }
}
